### ISSUE TITLE
Create a UHelper wiki with slash command /help or /info (Cindy)

### ISSUE THREAD

**Issue by xinyue296** [christianjokhaji/DiscordBot#22]
Please leave a brief introduction/description of your feature in the comments. Things you can include:
- The name of your feature, and what is the goal of this feature(s)?
- The commands related to these features, and what results shall the users calling them expect to see
- (Optional) A picture related
- A color of your choice (Note: default colors provided by Java is decent but limited. Plz provide a hex code of the color if u want to customize)

Here is a [sample embed](https://raw.githubusercontent.com/DV8FromTheWorld/JDA/assets/assets/docs/embeds/07-addField.png).

**Comment by xinyue296** [comment]
My plan for implementing this is to put each feature introduction into an embed and use a paginator for navigation.
What do u think?

**Comment by iDasher** [comment]
> My plan for implementing this is to put each feature introduction into an embed and use a paginator for navigation. What do u think?

That sounds smart though I can possibly see it getting a bit bulky maybe if there's a lot of pages people need to navigate through, can the paginator show like specific page names or do you think the /help can also have an additional component where the user does /help (name of feature)?

**Comment by xinyue296** [comment]
> > My plan for implementing this is to put each feature introduction into an embed and use a paginator for navigation. What do u think?
> 
> 
> 
> That sounds smart though I can possibly see it getting a bit bulky maybe if there's a lot of pages people need to navigate through, can the paginator show like specific page names or do you think the /help can also have an additional component where the user does /help (name of feature)?

Thanks for suggestions! Currently, our paginator does show page numbers, but it might be easier to navigate if we have a selectable menu. I also like the idea of having a help command for each of the feature since some of them have more commands, and the paginator are not clickable after 15 min😬

**Comment by iDasher** [comment]
My features name is the StudyHelper and its goal is to help students study by allowing them to create quizzes to practice off.

Features:

1. Add Question: Allows a user to add a question, answer and optional hint to the current quiz
2. Reset Notes: Reset current quiz to be empty
3. Study: Allows the user to study the quiz, being show a question and being able to display a hint if desired. (In Development, user will be able to write their answer and see if its correct or not, being given a final score at the end of the quiz)
4. Save Quiz: Saves quiz to the bot with a name so the user can use the quiz later
5. Load Quiz: Load a previously saved quiz.
6. (In Development) Check Scores: Check scores across multiple study sessions to see if you have been improving.

Color: Green(if that's taken maybe purple or blue?)

**Comment by Overpoweredplatypus** [comment]
The name of the feature is timer. Specifically, it's a pomodoro timer, where one can break a whole period of studying or working into intervals, separated by short breaks. The goal of this feature is to boost producivity between discord users within a server and to promote collaboration. 

Features:
1. Add timer: Users can configure how much they want to spend on work and how much they want to spend on breaks. They can input an integer to specify how many times they'd like to repeat. Discord users can make their own custom timer that suits their study habits, instead of the typical 25 minutes of work and 5 minutes of break routine. 
2. Delete timer: Users can delete a timer preset by giving its name! A user can have up to 5 presets.
3. Start timer: Starts a timer and you can optionally add other Discord users who also want to do something together so that they're also notified by the timer
4. Cancel timer: Cancels an ongoing timer. But, cancelling doesn't involve deactivating it; it's rather making it stop notifying you. 

Color: light purple (HEX code: ED73FA)

Description: A customizable pomodoro timer

**Comment by xinyue296** [comment]
Feature name: Find Recipe

Description: Find recipes with ingredients and nutritional info.

Feature:
`/find-recipe`: By entering a food and the number of recipes you want, UHelper will find related recipes for you, along with source recipes, required ingredients, and nutritional information, all powered by [Edmaman API](https://www.edamam.com/). Plus, by adding optional parameters, you can get more specific recipes suited to your needs :scroll:

Color: Orange

**Comment by christianjokhaji** [comment]
My features are the mini-games. Whenever you have a break or free time, call on one of the following commands to start it:

`/rock-paper-scissors your_choice` Starts a game of rock paper scissors.
`/trivia` Starts a game of true/false trivia.
`/8ball` Receive a Magic 8Ball reading.

Color: Cyan

**Comment by sailoraria** [comment]
Feature name: Schedule Reminder

Description: UHelper can schedule any ongoing exams, assignments, or general events for you and send you reminders via direct message 24 hours before your event, or an hour before the event if it was scheduled less than a day before. It will also automatically remove events from your schedule once they have passed.

Features:
`/schedule-event`: Enter the name of your event, the date in YYYY MM DD HR MIN format and UHelper will add this event to your schedule! You cannot schedule events in the past or duplicate events (ie. events with the exact same name and time).

 `/schedule-exam`: Enter the course code of your exam, the location of your exam, the date in YYYY MM DD HR MIN format and UHelper will add this exam to your schedule! You cannot schedule exams in the past or duplicate exams (ie. exams at the same time).

 `/schedule-assignment`: Enter the course code of the class that the assignment is from, the name of the assignment, the due date in YYYY MM DD HR MIN format and UHelper will add this assignment to your schedule! You cannot schedule assignments in the past or duplicate assignments (ie. assignments with the same course code AND the same name).

`/current-schedule`: Displays the user's ongoing scheduled events.

`/clear-event`: Allows the user to remove a specific event from their schedule. UHelper will display your current schedule in an indexed list and allow you to choose which indexed event you want to remove. You will also be unsubscribed from that event's reminder alert.

`/clear-schedule`: Clears all ongoing events from the user's schedule and unsubscribes them from all event reminders.

Colour: Pink :)
